### ISSUE TITLE
packDeploy returns SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by plekkie** [vlocityinc/vlocity_build#125]
Node.js v10.14.1
Vlocity Build v1.7.8

When running packDeploy to my sandbox, I get the following error:

```
Activated >> VlocityAction/RET_UpgradePlan
C:\Users\niels.plekkenpol\AppData\Roaming\npm\node_modules\vlocity\node_modules\sass.js\dist\sass.sync.js:61
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_W

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\niels.plekkenpol\AppData\Roaming\npm\node_modules\vlocity\lib\datapacks.js:52:33
    at C:\Users\niels.plekkenpol\AppData\Roaming\npm\node_modules\vlocity\node_modules\salesforce-alm\node_modules\jsforce\lib\promise.js:72:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Who can help me solve this matter?

**Comment by rutlabaga** [comment]
Can you upload a zip of the project being deployed or send to support@vlocity.com ?

**Comment by plekkie** [comment]
I sent an e-mail to Vlocity Support. Thanks for your advice @rutlabaga.
