### ISSUE TITLE
file access errors on windows: EPERM: operation not permitted during packExport

### ISSUE THREAD

**Issue by pjeschko** [vlocityinc/vlocity_build#206]
During pack export we nearly always get file access errors (9 out of 10 times). We are running the vlocity build tool script on node.js. version v10.15.3 and have the vlocity build tool version v1.11.0 on a windows 10 64 bit machine. We have already checked that we have the necessary permissions on the root folder we are exporting too.

Here is an extract of the latest errors logged:
Uncaught Error >> Export - Error: EPERM: operation not permitted, lstat 'vlocity\AttributeCategory\crm_BaseCategory\Attributes_ParentKeys.json'
    at Object.lstatSync (fs.js:840:3)
    at Object.lstatSync (C:\Users\jeschkp2\AppData\Roaming\npm\node_modules\vlocity\node_modules\graceful-fs\polyfills.js:295:24)
    at Object.rimrafSync [as removeSync] (C:\Users\jeschkp2\AppData\Roaming\npm\node_modules\vlocity\node_modules\fs-extra\lib\remove\rimraf.js:237:18)
    at items.forEach.item (C:\Users\jeschkp2\AppData\Roaming\npm\node_modules\vlocity\node_modules\fs-extra\lib\empty\index.js:39:12)
    at Array.forEach (<anonymous>)
    at Object.emptyDirSync (C:\Users\jeschkp2\AppData\Roaming\npm\node_modules\vlocity\node_modules\fs-extra\lib\empty\index.js:37:9)
    at module.exports.DataPacksExpand.processDataPack (C:\Users\jeschkp2\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksexpand.js:803:24)
Uncaught Error >> Export - Error: EPERM: operation not permitted, open 'D:\build\vlocity\vlocity\AttributeCategory\crm_BaseCategory\Attributes_ParentKeys.json'

**Comment by novarine** [comment]
case created: 00188217

**Comment by rutlabaga** [comment]
Handled through support
