### ISSUE TITLE
Starting OmniScript LWC Activation >> Loading Page taking too long - Retrying

### ISSUE THREAD

**Issue by ichweiss42** [vlocityinc/vlocity_build#393]
Hi. I have an issue with deploying vlocity packs to dev sandboxes. The puppeteer library cannot activate the new version of OmniScript because the response from the server takes too long. That works fine when deploying to Prod.

Starting OmniScript LWC Activation >> OmniScript/dc_lwc_English (a2s1l0000007cluAAA)  
   LWC Activation URL >> https://######.my.salesforce.com/apex/vlocity_cmt__OmniLwcCompile?id=a2s1l0000007cluAAA&activate=true  
   Result >> {"Status":"Deleted","VlocityDataPackId":"a5O1l0000000UKZEA2"}  
   Salesforce Org >> SIT  
   Version Info >> v1.14.2 vlocity_cmt 900.408  
   Log File >> vlocity-temp/logs/manifest-vlocity/pack-deploy-yaml-2021-08-05T09-12-21-519Z-Deploy.yaml  
   Current Status >> Deploy  
   Remaining >> 66  
   Success >> 72  
   Elapsed Time >> 0m 39s  
   Migrated 72 items >> Deploying  
   Error >> 0  
   Error >> TimeoutError: waiting for selector `#compiler-message` failed: timeout 30000ms exceeded
     at new WaitTask (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
     at DOMWorld.waitForSelectorInPage (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
     at Object.internalHandler.waitFor (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
     at DOMWorld.waitForSelector (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
     at Frame.waitForSelector (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:842:51)
     at Page.waitForSelector (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1285:33)
     at module.exports.OmniScript.compileOSLWC (/usr/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:232:46)
     at async module.exports.OmniScript.afterActivationSuccess (/usr/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:149:9)
     at async module.exports.DataPacksUtils.handleDataPackEvent (/usr/lib/node_modules/vlocity/lib/datapacksutils.js:2816:10)
     at async module.exports.DataPacksJob.activateAll (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:2014:13)
     at async module.exports.DataPacksJob.deployPack (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:2454:17)
     at async module.exports.UtilityService.runInputMap (/usr/lib/node_modules/vlocity/lib/utilityservice.js:211:13)
     at async Promise.all (index 1)
     at async module.exports.UtilityService.parallelLimit (/usr/lib/node_modules/vlocity/lib/utilityservice.js:233:13)
     at async module.exports.DataPacksJob.deployJob (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:2620:9)
     at async module.exports.DataPacksJob.doRunJob (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:337:9)  
   OmniScript/dc_lwc_English >> Loading Page taking too long - Retrying - Tries: 0 of 120

**Comment by hemnepal** [comment]
same issue

**Comment by ZanePearton** [comment]
+1, the same issue

**Comment by franPriggio** [comment]
Same here...

**Comment by pawel-id** [comment]
This is written in that way that it must fail from time. And it does. We are doing huge amount of deployment in out CI and see this every day or two.

This particular operation is performed via puppeteer. Puppeteer require some precautions when working with slow, complex and unreliable web pages. And Salesforce orgs definitely belong to that categories. Let's look into the code.

Initially the page is opened with authorization token. [see here](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/flexcard.js#L41) 

```javascript
  await Promise.all([
      page.waitForNavigation({ timeout: loginTimeout, waitUntil: 'load' }),
      page.waitForNavigation({ timeout: loginTimeout, waitUntil: 'networkidle2'}),
      page.goto(loginURl, {timeout: loginTimeout})
  ]);
```

Salesforce respond with series redirects. It is expected puppeteer will wait until complete authorization and redirect sequence. In most cases it works. But sometimes when Salesforce is lagging this part of code let to proceed further to next puppeteer action without completion of authorization sequence. 

Then it proceeds to [next operation](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/flexcard.js#L64) still doing current operation

```javascript
await page.goto(flexCardCompilePage, {timeout: loginTimeout});
```

Triggering this code breaks current incomplete authorization and try to proceed to compile page. Proceeding to compile page is unsuccessful due to lack of authorization. And the it retrying until it finally dies. [see here](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/flexcard.js#L72)

```javascript
while (tries < maxNumOfTries && !jobInfo.ignoreLWCActivationCards) {
  // redacted for clarity
  VlocityUtils.log('FlexCards LWC Activation', 'Loading Page taking too long - Retrying...)
}
```

This erroneous pattern is applied in 4 files and lead to the same problem:  [flexcard.js](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/flexcard.js), [omniscript.js](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/omniscript.js), [vlocitycard.js](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/vlocitycard.js), [vlocityuilayout.js](https://github.com/vlocityinc/vlocity_build/blob/v1.16.3/lib/datapacktypes/vlocityuilayout.js)

How to fix it? After initial `page.goto(loginURl,...)` there should some wait operation to make sure that initial login page has been opened completely. There could be multiple strategies. E.g.: waiting for some known selector which appears after successful operation (the selector below is little blue cloud header log).

```javascript
await page.waitForSelector('.slds-global-header__logo')
```

Obviously it should be also handled situation when this will take longer then expected or Salesforce will change layout and won't provide such selection in the future.

Final word: although puppeteer is great tool, using it for building that CLI is bad idea and that problem is good proof of that.

**Comment by lpsouzalima** [comment]
Hi, take a look if this patch CME 238.12.900.464.4 solve your problem.

**Issue:**
When you deactivated a single child reusable OmniScript referenced by 100 or more parent OmniScripts, you got an "APEX CPU Time Limit Exceeded" error.

**Article**:
https://help.salesforce.com/s/articleView?language=en_US&id=ind.comms_patch_releases_summer_22.htm&type=5

**Comment by ONoes** [comment]
Any updates for this issue?
