### ISSUE TITLE
Apex errors during deployment and crash due to out of memory

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#413]
We are observing random apex errors on deployment to scratch orgs like:

* APEX_ERROR: System.HandledException: ConcurrentPerOrgLongTxn Limit exceeded
* APEX_ERROR: System.NullPointerException: Argument cannot be null
* TimeoutError: Navigation timeout of 30000 ms exceeded

Single deployment can contain dozens of such entries. 

The scratch org at the moment of deployment is not used by humans or other processes. We are using VBT v 1.14.12 (we were spotting this since long time on previous versions). The command is regular deployment like `vlocity packDeploy -job vlo-app/other.yaml -sfdx.username $ALIAS --verbose`

After such issues the VBT gets killed due to out of memory.

Real error samples picked from failed pipeline:

```
Make Get Request Error >> APEX_ERROR: System.HandledException: ConcurrentPerOrgLongTxn Limit exceeded.

(System Code)
    at HttpApi.getError (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/vlocity/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/vlocity/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

```
Error >> APEX_ERROR: System.NullPointerException: Argument cannot be null.

(System Code)
    at HttpApi.getError (/usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/vlocity/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/vlocity/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

```
  TimeoutError: Navigation timeout of 30000 ms exceeded
    at /usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.navigateFrame (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:784:16)
    at async module.exports.OmniScript.compileOSLWC (/usr/local/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:231:13)
    at async module.exports.OmniScript.afterActivationSuccess (/usr/local/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:149:9)
    at async module.exports.DataPacksUtils.handleDataPackEvent (/usr/local/lib/node_modules/vlocity/lib/datapacksutils.js:2816:10)
    at async module.exports.DataPacksJob.activateAll (/usr/local/lib/node_modules/vlocity/lib/datapacksjob.js:2014:13)
    at async module.exports.DataPacksJob.deployPack (/usr/local/lib/node_modules/vlocity/lib/datapacksjob.js:2453:17)
    at async module.exports.UtilityService.runInputMap (/usr/local/lib/node_modules/vlocity/lib/utilityservice.js:211:13) 
```

**Comment by rutlabaga** [comment]
Can you file a Salesforce support ticket with the full log?
Make Get Request Error >> APEX_ERROR: System.HandledException: ConcurrentPerOrgLongTxn Limit exceeded.
This one is generally fine and will just retry. VBT is aggressive with concurrency so just assumes it will hit these sometimes if many DataPacks are taking a long time to deploy. 

For the other two it will heavily depend on why this is happening. The navigation timeout is a puppeteer issue but not sure if extending the time would make any difference or it is just failing. The NullPointerException would need to be investigated.

**Comment by pawel-id** [comment]
sure, here is salesforce support ticket #41687779
verbose logs attached to the ticket

**Comment by thvd** [comment]
@pawel-id It's been a while, how is this going? Already solved? We are facing similar issues. Both these issues we have as well: 
- APEX_ERROR: System.HandledException: ConcurrentPerOrgLongTxn Limit exceeded
- APEX_ERROR: System.NullPointerException: Argument cannot be null

**Comment by pawel-id** [comment]
@thvd I don't see this issue on 1.14.19 (or at least it doesn't break the pipelines). We tried to upgrade to 1.15.0 and it was happening radnomly and stopping our pipelines with error. We reverted to 1.14.19 and send the logs to @rutlabaga and granted a scratch org via our friend Madhava. Waiting for feeadback.

**Comment by thvd** [comment]
@pawel-id are you also using Azure Devops pipelines? As i am seeing this only in the pipelines (Azure Devops), but not when i locally (from laptop) deploy.

**Comment by pawel-id** [comment]
@thvd we are using Gitlab with k8s runners on GCP where it was happening. Didn’t check locally

**Comment by pawel-id** [comment]
I created a ticket #42406726 related to this issue on 1.15. @rutlabaga please findy the raw logs attached to the ticket

**Comment by AllanOricil** [comment]
@pawel-id do you see this issue when using local compilers?

**Comment by pawel-id** [comment]
> @pawel-id do you see this issue when using local compilers?

we don't use local compilers, still on puppeteer. see our thoughts https://github.com/vlocityinc/vlocity_build/issues/491

However the good thing is that the error is not happening recently, or at last for sure is not breaking our pipelines.
