### ISSUE TITLE
Linux Deploy Issue. 

### ISSUE THREAD

**Issue by mweiss427** [vlocityinc/vlocity_build#43]
Doing a packDeploy.   Here is the output I get while on a linux machine.   

Note the: hotfix/deduplicate_lists Branch works on a linux machine.
Doing it on a windows machine also works.  (on master)

TypeError: Object.values is not a function
    at DataPacksUtils.printJobStatus (/opt/vlocity_build/lib/datapacksutils.js:790:29)
    at DataPacksJob.deployJob (/opt/vlocity_build/lib/datapacksjob.js:1223:37)
    at DataPacksJob.doRunJob (/opt/vlocity_build/lib/datapacksjob.js:330:14)
    at /opt/vlocity_build/lib/datapacksjob.js:267:22
    at /opt/vlocity_build/lib/datapacksjob.js:265:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
  Uncaught Job Error >> {

**Comment by rutlabaga** [comment]
Please make sure you are using Node 8+. Object.values was added in Node 7, so that is most likely the issue.

**Comment by mweiss427** [comment]
You're correct, Sorry about that!
