### ISSUE TITLE
[Feature request] have installDPsfromStaticResource install static resource containing ZIP file

### ISSUE THREAD

**Issue by thvd** [vlocityinc/vlocity_build#478]
During the install of the LWC Cart i figured lets use the Vlocity Build Tool for this to automate this. 
I tried using the installDPsfromStaticResource command with this job file: 

```yaml
StaticResourceQuery: Select Name, Body from StaticResource where Name IN( 'CPQ_browse_flexcards', 'CPQ_cart_flexcards', 'CPQ_common_flexcards', 'CPQ_config_flexcards', 'CPQ_DR_IP_OS', 'CPQ_assets_flexcards')

```

But that fails with:

```bash

  Failed to Install >> CPQ_assets_flexcards SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at DataPacksJob.installFromStaticResourceQuery (/node_modules/vlocity/lib/datapacksjob.js:1983:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataPacksJob.installDPsfromStaticResource (/node_modules/vlocity/lib/datapacksjob.js:1960:9)
    at async DataPacksJob.doRunJob (/node_modules/vlocity/lib/datapacksjob.js:362:9)
    at async DataPacksJob.runJobWithInfo (/node_modules/vlocity/lib/datapacksjob.js:292:9)
    at async DataPacksJob.runJob (/node_modules/vlocity/lib/datapacksjob.js:94:26)
    at async Vlocity.runDataPacksCommand (/node_modules/vlocity/lib/vlocity.js:173:16)
    at async VlocityCLI.runJob (/node_modules/vlocity/lib/vlocitycli.js:724:12)
    at async VlocityCLI.runCommands (/node_modules/vlocity/lib/vlocitycli.js:612:23)  


```

My guess here is that `installFromStaticResourceQuery()` does not support ZIP file static resources. But that would be very welcome!

**Comment by thvd** [comment]
@rutlabaga  i want to make a Idea on the IdeaExchange, what would be the best way to do this? Which category?
