### ISSUE TITLE
Omniscript compiler fails even with Puppeteer installed

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#549]
Getting the following error when deploying and activating Vlocity datapacks with VBT. I have puppeteer installed in the deployment YAML.
Vlocity ver: vlocity@1.16.3
Puppeteer ver: puppeteer@19.4.1

"An error occurred while loading OmniScript compiler: Error: Failed to get package '@vlocity-cme/omniscript-lwc-compiler' Response error 401 Unauthorized  - If you are using Puppeteer for LWC compilation this error can be ignored."

**Comment by centricadean** [comment]
Happy New Year @irfanlai 

You need to raise a case with Salesforce to get your NPM key for the Vlocity repo. Once you have this, add it into your job file as per the instructions on the readme :)

**Comment by irfanlai** [comment]
@centricadean We have Github actions for our Vlocity deployment. Where should I be adding the NPM key? Not able to figure it out from the instructions.

**Comment by irfanlai** [comment]
@centricadean Thanks for the job file example. I added the npm repo key and when we tested with omniscript, it deployed but it failed when compiling the LWC component with the below error. Any idea what is missing?
I have added the job file that we are using and also the error below.

```
projectPath: ./vlocity
activate: true
autoRetryErrors: true
supportHeadersOnly: false
npmAuthKey: KEYHERE
npmRepository: 'https://repo.vlocity.com/repository/vlocity-public/'
gitCheck: true
queries:
```

```
Adding to Deploy >> OmniScript/Update_DealSetup_English - Update_DealSetup_English    
  Deploy >> 1 Items  
  Deploying >> OmniScript/Update_DealSetup_English  
  Result >> {"Finished":0,"Total":1,"Message":"Ready","Status":"Ready","VlocityDataPackId":"a5W7j000000LBfREAW","VlocityDataPackProcess":"Import"}  
  Result >> {"Finished":1,"Total":1,"Message":"Complete","Status":"Complete","VlocityDataPackId":"a5W7j000000LBfREAW","VlocityDataPackProcess":"Import"}  
  Deploy Success >> OmniScript/Update_DealSetup_English Deal Setup 1   
  Result >> {"VlocityDataPackId":"a5W7j000000LBfREAW","VlocityDataPackKeysToActivate":["ALL"],"Total":0,"Finished":0,"VlocityDataPacksActivated":[],"Status":"Complete","error":"OK","errorCode":"INVOKE-200","activationSuccess":[{"VlocityDataPackKey":"OmniScript/Update_DealSetup_English"}]}  
  Activated >> OmniScript/Update_DealSetup_English  
  Get Package Version  
  Loading @vlocity-cme/omniscript-lwc-compiler@latest  
  Starting OmniScript LWC Compilation >> OmniScript/Update_DealSetup_English (a307j000000ThN6AAK)  
  Retrieving OmniScript definition  
  Compiling OmniScript LWC Component  
Specified path does not exist. Creating it now...
  Parent OmniScript (OmniScript/PreOpportunityScreens_PreOpportunityScreens_English) for Reusable OmniScript (OmniScript/Update_DealSetup_English) will be compiled at the end  
  Result >> {"Status":"Deleted","VlocityDataPackId":"a5W7j000000LBfREAW"}  
  Salesforce Org >> ***  
  Version Info >> v1.17.0 vlocity_cmt 900.452  
  Log File >> vlocity-temp/logs/buildfiles/deploy_to_qa-yaml-2023-03-02T20-20-53-698Z-Deploy.yaml  
  Current Status >> Deploy  
  Error >> 0  
  Remaining >> 0  
  Success >> 1  
  Elapsed Time >> 0m 33s  
  Saving File Start  
  Saving File End >> 384  
  Checking Valid Imports Start  
  Parent OmniScripts to Compile >> [
    "OmniScript/PreOpportunityScreens_PreOpportunityScreens_English"
]  
  Starting Parent OmniScript LWC Activation >> Number of OmniScript to Activate: 1  
  Get Package Version  
  Starting OmniScript LWC Compilation >> OmniScript/PreOpportunityScreens_PreOpportunityScreens_English (a304w00000WhyLNAAZ)  
  Retrieving OmniScript definition  
  Compiling OmniScript LWC Component  
Specified path does not exist. Creating it now...
  Deploying generated LWC components  
  Using salesforce-alm  
  Running source:convert  
Using specified username ***

  {
    "name": "UnexpectedFileFound"
}  
  UnexpectedFileFound: Unexpected file found in package directory: /home/runner/work/salesforce-ses/salesforce-ses/force-app/main/default/ChannelObjectLinkingRules/Match_phone_number_to_record_1623529206154.ChannelObjectLinkingRule-meta.xml
```

**Comment by centricadean** [comment]
I've not seen that error before @irfanlai, you might need to raise a Salesforce case for that. I've noticed that you're on 900.452 which is quite out of date. Support will want you to upgrade to the latest package. You could give that a go first, and then if it still doesn't work, raise the case.

**Comment by irfanlai** [comment]
Thanks for your quick reply. I rolled back the change but now every time an OS is getting deployed we are getting this error.
I raised a bug in VBT here. I will close it for now and raise a case with Salesforce.

**Comment by irfanlai** [comment]
> I've not seen that error before @irfanlai, you might need to raise a Salesforce case for that. I've noticed that you're on 900.452 which is quite out of date. Support will want you to upgrade to the latest package. You could give that a go first, and then if it still doesn't work, raise the case.

If 900.452 is out of date what should it be and does Salesforce update this or we have to do it?

**Comment by irfanlai** [comment]
We raised the case with Salesforce and the response was to check the file which is in the logs. 
The file in question is not even being used in the deploying datapacks. So the question is does VBT checks for any file discrepancies or it checks if all files in the repo is in good state, no git error etc?

'UnexpectedFileFound: Unexpected file found in package directory: /home/runner/work/salesforce-ses/salesforce-ses/force-app/main/default/ChannelObjectLinkingRules/Match_phone_number_to_record_1623529206154.ChannelObjectLinkingRule-meta.xml'

**Comment by irfanlai** [comment]
Does anyone know if VBT checks for file issues in the repo? Every time we delete the file mentioned in error in the next run we get a new file with the error.

Below is the latest log.

```
Deploying generated LWC components  
  Using salesforce-alm  
  Running source:convert  
Using specified username ***

  {
    "name": "UnexpectedFileFound"
}  
  UnexpectedFileFound: Unexpected file found in package directory: /home/runner/work/salesforce-ses/salesforce-ses/force-app/main/default/audience/AcctWithMultipleBillingAccounts.audience-meta.xml
    at Workspace.isValidSourcePath (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:165:35)
    at Workspace.handleArtifact (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:148:18)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:138:36)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walkDirectories (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:125:13)
    at async Workspace.initializeStateFull (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:95:9)
    at async Workspace.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:47:17)
    at async Workspace.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/core/node_modules/@salesforce/kit/lib/creatable.js:31:9)
    at async SourcePathStatusManager.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourcePathStatusManager.js:161:26)
    at async SourcePathStatusManager.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceWorkspaceAdapter.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:61:21)
    at async SourceWorkspaceAdapter.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceConvertApi.initWorkspaceAdapter (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:53:43)
    at async SourceConvertApi.doConvert (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:59:9)  
  Saving File Start  
  Saving File End >> 547  
  Retrying Deployment  
  Finalizing Deployment  
  Finalizing Deployment  
  Salesforce Org >> ***  
  Error >> 0  
  Version Info >> v1.17.1 vlocity_cmt 900.452  
  Log File >> vlocity-temp/logs/buildfiles/deploy_to_qa-yaml-2023-04-03T16-50-51-922Z-Deploy.yaml  
  Current Status >> Deploy  
  Remaining >> 0  
  Success >> 18  
  Elapsed Time >> 2m 0s  
  Migrated 18 items >> Deploying  
  Formatting Response >> Deploy  
  DataRaptor/GetOrderEFL >> Success  
  DataRaptor/US_GetMatrixData >> Success  
  DataRaptor/US_UpsertCommodityOrderProduct >> Success  
  IntegrationProcedure/Customer_RenewalCreateInitialOrder >> Success  
  IntegrationProcedure/Enrollment_GetProductsforEnrollments >> Success  
  IntegrationProcedure/Enrollment_Products >> Success  
  IntegrationProcedure/Enrollment_RenewContract >> Success  
  IntegrationProcedure/Enrollment_UpsertCommodityOrderProduct >> Success  
  IntegrationProcedure/Generate_PlanDocument >> Success  
  IntegrationProcedure/Renew_ProcessPlansEFL >> Success  
  OmniScript/AgentServices_RenewContract_English >> Success  
  OmniScript/Customer_RenewContract_English >> Success  
  OmniScript/Enrollment_AddServiceAddress_English >> Success  
  OmniScript/Plan_URL_English >> Success  
  VlocityCard/US_ProductSelect >> Success  
  VlocityCard/ViewPlanURL >> Success  
  VlocityCard/ViewPlanURL_DataTable >> Success  
  VlocityCard/ViewPlanURL_DataTableChild >> Success  
  Saving File Start  
  Saving File End >> 829  
  Job Complete >> Deploy 2m 0s  
Deploy error:
Exception while deploying compiled LWC components:
{
  "name": "UnexpectedFileFound"
}
Error: Process completed with exit code 1.
```

**Comment by pawel-id** [comment]
same here on latest VBT v1.17.2. 100% reproducible. The file which is reported as 'unexpected' is not Vlocity related. It is regular Salesforce metadata in sibling folder. It seems that for some reason VBT is trying to apply convert operation on files outside of its scope.

```
  Salesforce Org >> sc1  
  Version Info >> v1.17.2 vlocity_cmt 900.456  
  Current Status >> Deploy  
  Remaining >> 0  
  Success >> 1  
  Error >> 0  
  Elapsed Time >> 0m 30s  
  Deploying generated LWC components  
  Using salesforce-alm  
  Running source:convert  
  {
    "name": "UnexpectedFileFound"
}  
  UnexpectedFileFound: Unexpected file found in package directory: /Users/pawel/wrk/spartakus/navio/navio/force-app/self-service/audience/Billing_Account.audience-meta.xml
    at Workspace.isValidSourcePath (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:165:35)
    at Workspace.handleArtifact (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:148:18)
    at async Workspace.walk (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:138:36)
    at async Workspace.walk (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walkDirectories (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:125:13)
    at async Workspace.initializeStateFull (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:95:9)
    at async Workspace.init (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:47:17)
    at async Workspace.create (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/@salesforce/core/node_modules/@salesforce/kit/lib/creatable.js:31:9)
    at async SourcePathStatusManager.init (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourcePathStatusManager.js:161:26)
    at async SourcePathStatusManager.create (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceWorkspaceAdapter.init (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:61:21)
    at async SourceWorkspaceAdapter.create (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceConvertApi.initWorkspaceAdapter (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:53:43)
    at async SourceConvertApi.doConvert (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:59:9)
    at async SourceConvertCommand.execLegacyCommand (/Users/pawel/.nvm/versions/node/v18.16.0/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/ToolbeltCommand.js:148:29)
...
```

We were trying to use `useSfdxCli: true` which makes that error is not happening, but it leads to another issues which are out of scope of this ticket.

**Comment by AllanOricil** [comment]
If u share an sfdx project with the problem I can repro and try to fix the cli. Right now it is impossible.

**Comment by AllanOricil** [comment]
AMAZING SUPPORT!

**Comment by AllanOricil** [comment]
I think I understood what is happening now. I can fix it if sf assigns someone to review and approve PRs...

@sbutterfield

**Comment by irfanlai** [comment]
Just checking this thread after a long time, finally there has been updates here so I am not the only one having this issue.

@AllanOricil Do you have a fix for this? I need this so very urgently as whenever we have an OS deployment using GIT, we have to manually go and activate them and it takes a good amount of time for us.

**Comment by AllanOricil** [comment]
If salesforce hires my company's services I can give maintenance on this cli 😎🤓🥸

LET'S DO A DEAL!

@ssbutters

**Comment by AllanOricil** [comment]
I promise to win an Oscar and not charge 10 kk a year

WHAT A BUDGET!
