### ISSUE TITLE
Running source:convert -- UnexpectedFileFound

### ISSUE THREAD

**Issue by tggagne** [vlocityinc/vlocity_build#555]
tgagne@HWKMAC-C02DN69QMD6M adjustments % vlocity -version
  Vlocity Build v1.16.2  

---  

`Deploying generated LWC components  
  Using salesforce-alm  
  Running source:convert  
  {
    "name": "UnexpectedFileFound"
}  
  UnexpectedFileFound: Unexpected file found in package directory: /Users/tgagne/git/dx-mga/force-app/main/default/vlocity/AttributeCategory/adjustments/Adjustments_Attributes.json
    at Workspace.isValidSourcePath (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:165:35)
    at Workspace.handleArtifact (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:148:18)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:138:36)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walkDirectories (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:125:13)
    at async Workspace.initializeStateFull (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:95:9)
    at async Workspace.init (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:47:17)
    at async Function.create (/Users/tgagne/var/node_modules/@salesforce/kit/lib/creatable.js:31:9)
    at async SourcePathStatusManager.init (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourcePathStatusManager.js:161:26)
    at async Function.create (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceWorkspaceAdapter.init (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:61:21)
    at async Function.create (/Users/tgagne/var/node_modules/vlocity/node_modules/salesforce-alm/node_modules/@salesforce/kit/lib/creatable.js:20:9)`

**Comment by irfanlai** [comment]
@tggagne I am encountering the same issue today after adding the NPM key to my job file.

If I check sdfx-project.json there is no change and the content is as follows. 

**{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "name": "Salesforce_Project_Repo",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "55.0"
}
**

**Comment by pawel-id** [comment]
seems duplicate https://github.com/vlocityinc/vlocity_build/issues/549 . Unfortunately not fixed yet

**Comment by tggagne** [comment]
We've "kinda" worked around it by simply deleting `sfdx-project.json` before the deploy so vbt can built its own, then we `git checkout -- sfdx-project.json` to restore the file afterward.

It's a workaround, not a fix, but I thought I'd share it regardless.
