### ISSUE TITLE
Started getting this error today when deploying Omniscript

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#569]
We added the NPM repo key today and we got the below error when deploying Omniscript. So we rolled back the NPM changes from the job file but still, we are getting the same error. Any idea what's wrong or did anything change? 
Note: This was working perfectly fine today morning between 8.30 am to 9 am CT. This started after 10.30 am CT.

```
Salesforce Org >> ***  
  Version Info >> v1.17.0 vlocity_cmt 900.452  
  Log File >> vlocity-temp/logs/buildfiles/deploy_to_qa-yaml-2023-03-02T20-20-53-698Z-Deploy.yaml  
  Current Status >> Deploy  
  Error >> 0  
  Remaining >> 0  
  Success >> 1  
  Elapsed Time >> 0m 33s  
  Saving File Start  
  Saving File End >> 384  
  Checking Valid Imports Start  
  Parent OmniScripts to Compile >> [
    "OmniScript/PreOpportunityScreens_PreOpportunityScreens_English"
]  
  Starting Parent OmniScript LWC Activation >> Number of OmniScript to Activate: 1  
  Get Package Version  
  Starting OmniScript LWC Compilation >> OmniScript/PreOpportunityScreens_PreOpportunityScreens_English (a304w00000WhyLNAAZ)  
  Retrieving OmniScript definition  
  Compiling OmniScript LWC Component  
Specified path does not exist. Creating it now...
  Deploying generated LWC components  
  Using salesforce-alm  
  Running source:convert  
Using specified username ***

  {
    "name": "UnexpectedFileFound"
}  
  UnexpectedFileFound: Unexpected file found in package directory: /home/runner/work/salesforce-ses/salesforce-ses/force-app/main/default/ChannelObjectLinkingRules/Match_phone_number_to_record_1623529206154.ChannelObjectLinkingRule-meta.xml
    at Workspace.isValidSourcePath (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:165:35)
    at Workspace.handleArtifact (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:148:18)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:138:36)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walk (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:140:17)
    at async Workspace.walkDirectories (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:125:13)
    at async Workspace.initializeStateFull (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:95:9)
    at async Workspace.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/workspace.js:47:17)
    at async Workspace.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/core/node_modules/@salesforce/kit/lib/creatable.js:31:9)
    at async SourcePathStatusManager.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourcePathStatusManager.js:161:26)
    at async SourcePathStatusManager.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceWorkspaceAdapter.init (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceWorkspaceAdapter.js:61:21)
    at async SourceWorkspaceAdapter.create (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/@salesforce/kit/lib/creatable.js:20:9)
    at async SourceConvertApi.initWorkspaceAdapter (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:53:43)
    at async SourceConvertApi.doConvert (/home/runner/sfdx/lib/node_modules/vlocity/node_modules/salesforce-alm/dist/lib/source/sourceConvertApi.js:59:9)  
```

**Comment by irfanlai** [comment]
Closing as this is being tracked in https://github.com/vlocityinc/vlocity_build/issues/549
