### ISSUE TITLE
Error "Invalid URI" running packExport

### ISSUE THREAD

**Issue by soulberto** [vlocityinc/vlocity_build#570]
I got the following error running **vlocity -job Platform.yaml packExport**:

`Error: Invalid URI "/services/data/v54.0/query?q=SELECT%20Id%2C`

Full error message:
```Bash
Vlocity Build v1.17.0  
  Retrieving Vlocity  
Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20undefinedType__c%2C%20undefinedSubType__c%2C%20undefinedLanguage__c%2C%20undefinedIsLwcEnabled__c%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedOmniScript__c%20WHERE%20undefinedIsActive__c%20%3D%20true%20AND%20undefinedIsProcedure__c%20%3D%20false"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20undefinedType__c%2C%20undefinedSubType__c%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedOmniScript__c%20WHERE%20undefinedIsActive__c%20%3D%20true%20AND%20undefinedIsProcedure__c%20%3D%20true"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20Name%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedDRBundle__c%20WHERE%20undefinedType__c%20!%3D%20'Migration'"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
  VlocityDataPackType >> OmniScript  
  Query >> Select Id, undefinedType__c, undefinedSubType__c, undefinedLanguage__c, undefinedIsLwcEnabled__c,CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate FROM undefinedOmniScript__c WHERE undefinedIsActive__c = true AND undefinedIsProcedure__c = false  
  Query Error >> Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20undefinedType__c%2C%20undefinedSubType__c%2C%20undefinedLanguage__c%2C%20undefinedIsLwcEnabled__c%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedOmniScript__c%20WHERE%20undefinedIsActive__c%20%3D%20true%20AND%20undefinedIsProcedure__c%20%3D%20false"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)  
  VlocityDataPackType >> IntegrationProcedure  
  Query >> Select Id, undefinedType__c, undefinedSubType__c,CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate FROM undefinedOmniScript__c WHERE undefinedIsActive__c = true AND undefinedIsProcedure__c = true  
  Query Error >> Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20undefinedType__c%2C%20undefinedSubType__c%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedOmniScript__c%20WHERE%20undefinedIsActive__c%20%3D%20true%20AND%20undefinedIsProcedure__c%20%3D%20true"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)  
  VlocityDataPackType >> DataRaptor  
  Query >> Select Id, Name,CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate FROM undefinedDRBundle__c WHERE undefinedType__c != 'Migration'  
  Query Error >> Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20Name%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedDRBundle__c%20WHERE%20undefinedType__c%20!%3D%20'Migration'"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)  
  Initializing Project  
Error: Invalid URI "/services/data/v54.0/query?q=SELECT%20Id%2C%20NamespacePrefix%2C%20DeveloperName%2C%25vlocity_namespace%25__DefaultImportLimit__c%2C%25vlocity_namespace%25__DefaultExportLimit__c%20FROM%20%25vlocity_namespace%25__VlocityDataPackConfiguration__mdt"
    at Request.init (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:273:31)
    at new Request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/request.js:127:8)
    at request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:53:10)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/request/index.js:100:12
    at createRequest (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:84:13)
    at promise.then (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/transport.js:43:5)
    at HttpApi.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/http-api.js:82:47)
    at Connection.request (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/connection.js:332:18)
    at /Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/jsforce/lib/query.js:410:23
    at tryCallOne (/Users/slorenzotgmail.com/.nvm/versions/node/v19.0.0/lib/node_modules/vlocity/node_modules/promise/lib/core.js:37:12)
  Query Error >> SELECT Id, NamespacePrefix, DeveloperName,DefaultImportLimit__c,DefaultExportLimit__c FROM VlocityDataPackConfiguration__mdt Invalid URI "/services/data/v54.0/query?q=SELECT%20Id%2C%20NamespacePrefix%2C%20DeveloperName%2C%25vlocity_namespace%25__DefaultImportLimit__c%2C%25vlocity_namespace%25__DefaultExportLimit__c%20FROM%20%25vlocity_namespace%25__VlocityDataPackConfiguration__mdt"  
  Finishing Retrieve  
  Job Complete >> Export   
Export success:
0 Completed
```

**Comment by soulberto** [comment]
It looks like a auth org error, I tried again Auth the Org and now it's working...

**Comment by mvaria86** [comment]
@soulberto - What do you mean by tried again the Org? I am facing the issue, appreciate your help here.

**Comment by DaveHetesi** [comment]
@mvaria86 Did you get this resolved? I tried re-authorizing my org and still get this error.
