### ISSUE TITLE
Error while running vlocity pack deploy

### ISSUE THREAD

**Issue by sumit-chaturvedi-sf** [vlocityinc/vlocity_build#587]
Uncaught Job Error >> TypeError: dataPack.VlocityDataPackData.DRBundle__c[0].DRMapItem__c.forEach is not a function
    at DataRaptor.addParentReference (/opt/homebrew/lib/node_modules/vlocity/lib/datapacktypes/dataraptor.js:7:114)
    at DataPacksUtils.handleDataPackEventSync (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksutils.js:2841:39)
    at DataPacksUtils.updateDataPackWithNewMappings (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksutils.js:5054:14)
    at /opt/homebrew/lib/node_modules/vlocity/lib/datapacksbuilder.js:244:49
    at Array.forEach (<anonymous>)
    at DataPacksBuilder.buildImport (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksbuilder.js:242:38)
    at async DataPacksJob.deployJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:2657:28)
    at async DataPacksJob.doRunJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:339:9)
    at async DataPacksJob.runJobWithInfo (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:293:9)
    at async DataPacksJob.runJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:95:26) TypeError: dataPack.VlocityDataPackData.DRBundle__c[0].DRMapItem__c.forEach is not a function
    at DataRaptor.addParentReference (/opt/homebrew/lib/node_modules/vlocity/lib/datapacktypes/dataraptor.js:7:114)
    at DataPacksUtils.handleDataPackEventSync (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksutils.js:2841:39)
    at DataPacksUtils.updateDataPackWithNewMappings (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksutils.js:5054:14)
    at /opt/homebrew/lib/node_modules/vlocity/lib/datapacksbuilder.js:244:49
    at Array.forEach (<anonymous>)
    at DataPacksBuilder.buildImport (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksbuilder.js:242:38)
    at async DataPacksJob.deployJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:2657:28)
    at async DataPacksJob.doRunJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:339:9)
    at async DataPacksJob.runJobWithInfo (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:293:9)
    at async DataPacksJob.runJob (/opt/homebrew/lib/node_modules/vlocity/lib/datapacksjob.js:95:26)  
  Job Complete >> Deploy

**Comment by sumit-chaturvedi-sf** [comment]
Logged by mistake

**Comment by pawel-id** [comment]
I would advise you to check the structure of the failing Dataraptor. It is possible some file is missing within Dataraptor folder. VBT doesn't validate schema of its files and just fail in such scenarios.

Optionally do the proper packExport again from your source org and compare the outcome.
