### ISSUE TITLE
How can we create a manifest/job file(yaml) file using vlocity CLI with available datapackbs from repository?

### ISSUE THREAD

**Issue by ar-srinivas** [vlocityinc/vlocity_build#633]
How can we create a manifest/job file(yaml) file using vlocity CLI with available datapackbs from repository?

If the Vlocity CLI doesn't support this, do we have any alternative?

**Comment by pawel-id** [comment]
`vlocity packGetAllAvailableExports --nojob`

see [readme](https://github.com/vlocityinc/vlocity_build?tab=readme-ov-file#using-the-vlocitydatapackkey-in-the-manifest)

**Comment by ar-srinivas** [comment]
@pawel-id thank you for the response!

When we run this command, we are getting the below error. Looks like it is trying to query on salesforce but our context doesn't have a salesforce org, we are trying to create the manifest from the available datapacks in a folder(version control).

_VlocityDataPackType >> VqResource  
Query >> Select Id, Name,CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate FROM undefinedVqResource__c  
Query Error >> Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20Name%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedVqResource__c"
    at Request.init (/usr/local/lib/node_modules/vlocity/node_modules/request/request.js:273:31)_

**Comment by AllanOricil** [comment]
> @pawel-id thank you for the response!
> 
> When we run this command, we are getting the below error. Looks like it is trying to query on salesforce but our context doesn't have a salesforce org, we are trying to create the manifest from the available datapacks in a folder(version control).
> 
> _VlocityDataPackType >> VqResource Query >> Select Id, Name,CreatedBy.Name, CreatedDate, LastModifiedBy.Name, LastModifiedDate FROM undefinedVqResource__c Query Error >> Error: Invalid URI "/services/data/v54.0/query?q=Select%20Id%2C%20Name%2CCreatedBy.Name%2C%20CreatedDate%2C%20LastModifiedBy.Name%2C%20LastModifiedDate%20FROM%20undefinedVqResource__c" at Request.init (/usr/local/lib/node_modules/vlocity/node_modules/request/request.js:273:31)_

@ar-srinivas you have to do a local diff instead of org diff. With local diff those queries won't run.

**Comment by tiagonnascimento** [comment]
I wrote a JS script to do that. This script will write multiple manifest files, segregated by datapack types in a pre-established sequence/order. 

`const fs = require("fs");
const path = require("path");
const YAML = require("yaml");

// Define the order of datapack types
const order = [
  "GeneralSettings",
  "CpqConfigurationSetup",
  "CustomFieldMap",
  "VlocityPicklist",
  "AttributeCategory",
  "ObjectClass",
  "UIFacet",
  "UISection",
  "ObjectLayout",
  "TimePolicy",
  "PricingVariable",
  "ContextScope",
  "ContextDimension",
  "Pricebook2",
  "PriceList",
  "EntityFilter",
  "OrchestrationPlanDefinition",
  "Product2",
  "Rule",
  "Promotion",
  "Catalog",
  "Document",
  "ContentVersion",
  "DocumentTemplate",
  "VlocityStateModel",
  "ContractType",
  "VlocityAttachment",
  "DataRaptor",
  "IntegrationProcedure",
  "VlocityAction",
  "VlocitySearchWidgetSetup",
  "VlocityCard",
  "FlexCard",
  "OmniScript",
  "IntegrationRetryPolicy",
  "System",
  "InterfaceImplementation",
  "ItemImplementation",
  "ManualQueue",
  "ThorOrchestrationQueue",
  "OrchestrationQueueAssignmentRule",
  "OrchestrationItemDefinition",
  "OrchestrationDependencyDefinition"
  //  "DecisionMatrix", TODO: evaluate why failling
];

// Base directory path
const basePath = "./datapacks/";
const manifestPath = "./manifest/";

// Create YAML files
async function generateIndustriesManifests() {
  const buildfile = [];
  let i = 1;

  order.forEach((datapackType) => {
    const datapackTypePath = path.join(basePath, datapackType);
    const manifests = [];

    try {
      const datapackNames = fs
        .readdirSync(datapackTypePath)
        .filter((file) =>
          fs.statSync(path.join(datapackTypePath, file)).isDirectory()
        );

      datapackNames.forEach((name) => {
        manifests.push(`${datapackType}/${name}`);
      });

      const yamlContent = YAML.stringify({
        projectPath: "./datapacks/",
        expansionPath: ".",
        manifest: manifests,
        delete: true,
        activate: true,
        compileOnBuild: true,
        continueAfterError: true,
        autoRetryErrors: true,
        useAllRelationships: false,
        supportHeadersOnly: true,
        supportForceDeploy: true,
        npmAuthKey:
          "Y3VzdG9tZXJfYmFuY29fZGVsX2VzdGFkb19kZV9jaGlsZTpQZkFhYlJaQmhyNU1DMVRY"
      });

      const filename = `${String(i++).padStart(
        2,
        "0"
      )}-sfi-baseline-${datapackType}.yaml`;
      fs.writeFileSync(`${manifestPath}${filename}`, yamlContent);

      console.log(`Created: ${filename}`);

      buildfile.push({
        type: "datapack",
        manifestFile: `${manifestPath}${filename}`
      });
    } catch (error) {
      console.log(`Failed to create YAML for ${datapackType}:`, error);
      console.log("Continuing to the next datapack type");
    }
  });

  fs.writeFileSync(
    `${manifestPath}buildfileSequence.json`,
    JSON.stringify(buildfile, null, 4)
  );
  console.log("Created: buildfileSequence.json");
  console.log("Script finalized successfully");
}

generateIndustriesManifests();
`
